name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Setup Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install ESP8266 platform
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266
        
    - name: Compile firmware
      run: |
        mkdir -p firmware_build
        arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir firmware_build ESP8266_Firmware/OTA_Secure/OTA_Secure.ino
        
    - name: Rename firmware
      run: |
        cd firmware_build
        mv OTA_Secure.ino.bin firmware.bin || true
        
    - name: Generate SHA256
      run: |
        cd firmware_build
        sha256sum firmware.bin > sha256.txt
        SHA256=$(sha256sum firmware.bin | awk '{print $1}')
        echo "SHA256=$SHA256" >> $GITHUB_ENV
        echo "SHA256 Hash: $SHA256"
        
    - name: Create manifest
      run: |
        cd firmware_build
        cat > manifest.json << EOF
        {
          "version": "${{ github.ref_name }}",
          "firmware_url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/firmware.bin",
          "sha256": "${{ env.SHA256 }}",
          "build_date": "$(date -I)",
          "description": "Auto-generated build",
          "min_version": "1.0.0"
        }
        EOF
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          firmware_build/firmware.bin
          firmware_build/manifest.json
          firmware_build/sha256.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-build
        path: firmware_build/
